# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
 - jekyll-seo-tag
gems:
 - jekyll-feed
port: 3000
safe: true

name: Nenad Bubalo - Mouse On The Keys Blog`s
description: A description for your blog
url: https://mouseonthekeys.github.io/
# edit here to achieve your personal greatness

#baseurl: http://mouseonthekeys.github.io/
title: Nenad Bubalo
author: Nenad Bubalo
description: Personal blog and resume
avatar: slika.png
email: nenad.bubalo@mail.com
facebook: nenad.bubalo
github: mouseonthekey # username
instagram: grumpyraccoon
lastfm: MouseOnTheKeyz
#twitter: username
#linkedin: username
xing: Nenad_Bubalo
stackoverflow: users/11832202/mouse-on-the-keys   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: mouseonthekeys
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
